### ISSUE TITLE
Suggestion: Auto-Filtering Results when searching on RAM

### ISSUE THREAD

**Issue by eldexterr** [RetroAchievements/RAIntegration#484] opened 2019-11-17 18:43 UTC
On Dolphin an Bizhawk there an option that let you filter addresses automatically each frame until you desactivate it, very useful tbh.

For example "Filter all values != 0" until I deactivate it

**Comment by Jamiras** [comment] 2019-11-17 19:03
duplicate of #107.

**Closed by Jamiras** 2019-11-17 19:03 UTC
