### ISSUE TITLE
"Achievement Sets" Sorting

### ISSUE THREAD

**Issue by wilhitewarrior** [RetroAchievements/RAIntegration#465] opened 2019-10-18 21:33 UTC
I think having core/unofficial achievements sorted in their proper display order in the 'achievement sets' window would be helpful.  Personally, I tend to group my achievements by type and it makes it easy to find the one I'm looking for, especially with a game like Resident Evil 2 or Metal Gear Solid where there are many of them.

Also useful I think would be a 'move up' or 'move down' button to sort them out in the local achievements section. I know it can be done by editing the .txt file but this would just make it simpler I think. :)

**Comment by Jamiras** [comment] 2019-10-20 22:31
Duplicate of #8, which suggests sorting by column. Adding move up/move down is the next logical step and not specifically mentioned there.

See also #130 - changing sort order in the editor (for achievements uploaded to the server) will not affect the order on the server.

**Comment by meleu** [comment] 2020-01-07 04:08
closing as duplicate (see #8).

**Closed by meleu** 2020-01-07 04:08 UTC
Labels: duplicate
