### ISSUE TITLE
Achievement ordering does not work in the toolkit GUI

### ISSUE THREAD

**Issue by rzumer** [RetroAchievements/RAIntegration#409] opened 2019-07-03 22:16 UTC
Columns in the achievement editor can be highlighted, but clicking on them seems to do nothing. In addition, there does not seem to be a consistent order. I assume the order is based on the local data, but it does not always correspond to ID ordering.

Assuming ordering is not supported, the columns should be clearly static, and not change color when hovered over.

**Comment by Jamiras** [comment] 2019-07-03 22:21
I consider this a duplicate of #8, it's definitely a duplicate of #153 which I also marked as a duplicate of #8.

The order is based on local data for local achievements. Core and Unofficial achievements are ordered however they're received from the server.

**Comment by rzumer** [comment] 2019-07-03 22:33
That's fair, though the angle I'm taking is not that of a feature request but rather of a UI "bug", in that columns should not be highlight-able while sorting is not available.

**Closed** 2021-08-21 05:56 UTC
Labels: Achievement Editor
