### ISSUE TITLE
Memory Inspector Results Increase when searching for 4-bits

### ISSUE THREAD

**Issue by magusLOGS** [RetroAchievements/RAIntegration#293] opened 2019-02-01 15:42 UTC
The latest Toolkit version from 2019-02-01 has a issue where the number of results increase randomly when searching for 4-bits instead of always decreasing.

![Results increase 4-bits](https://i.imgur.com/zHClsr3.gif)

Tested and replicated it in following Emulators and RALibRetro Cores.

- RAVBA (Gameboy)
- RALibRetro (Gamebattle)
- RALibRetro (FCEUmm)
- RaLibRetro (Snes9x)

All of them are affected so i assume its a global issue and more if not all Emus/Cores are affected by it, it only happens when searching for 4-bits.

**Comment by Keltron3030** [comment] 2019-02-01 16:17
I thought that issue was resolved with https://github.com/RetroAchievements/RAIntegration/pull/210

**Comment by magusLOGS** [comment] 2019-02-02 16:18
The **GIF** above is from RAVBA 0.56 Toolkit 0.74, which always downloads the latest Toolkit version on startup, so for me its 2019-02-01.

I've deleted the Toolkit and redownloaded it and its still the exaxt same version **12414bcebe16602224762603ac8568f9**. This is the Toolkit version i get when autoupdating it.

**Comment by Jamiras** [comment] 2019-02-02 16:31
0.74 is the published toolkit, and the version that will be downloaded if you use the emulator.

![image](https://user-images.githubusercontent.com/32680403/52166648-2573ad80-26cd-11e9-88d4-2b05ed5ea1bf.png)

The 0.75 builds are in the #developer-news channel on discord. The "release candidate" is 0.74.124.0:

![image](https://user-images.githubusercontent.com/32680403/52166653-30c6d900-26cd-11e9-8581-2cf5d9d2a735.png)

To use a non-published version, you have to download it from discord and unzip it into your emulator directory.

**Comment by Jamiras** [comment] 2019-02-02 16:33
So, while you may have downloaded it on 2019-02-01, it's the dll that was published on 2018-09-08, and does not include the fix made for #210. 

Closing as duplicate of #210.

**Closed by Jamiras** 2019-02-02 16:33 UTC
