### ISSUE TITLE
Missing licensing information

### ISSUE THREAD

**Issue by rzumer** [RetroAchievements/RAIntegration#241] opened 2019-01-10 07:40 UTC
Since I am linking to `RAIntegration` and using the interface directly in my software, I would like to include applicable licensing information for it in my releases. As we are linking dynamically I believe even GPL would be compatible with the revised BSD license of QUASI88, but if there is no particular reason for choosing GPL over other more permissive licenses I would recommend at least LGPL, or a non-copyleft license.

Licensing information is typically added via a `LICENSE` or `LICENSE.txt` file at the root of the repository, and GitHub has presets for many.

**Comment by Jamiras** [comment] 2019-01-10 14:32
Duplicate of #20. The last time I brought up the topic, I proposed using GPL as that's what all of the other emulators use. For the dll itself, it's not that important. The stuff we really have to protect is in rcheevos now, which is currently using MIT just so we had _something_ so we could try to get it into RetroArch.

**Closed** 2019-01-10 14:32 UTC

**Comment by rzumer** [comment] 2019-01-10 15:42
My bad, I missed that issue. However the situation is a bit different now, as at least Meka and (RA)QUASI88 are licensed under BSD or a variant thereof. That said, what the emulators are licensed under should not matter as long as we use a license which allows them to remain compatible. GPL is fine for GPL emulators, however if a non-GPL emulator is using Integration code and not merely linking to it, it may not be compatible with a GPL Integration.

As long as this is not the case, I think that GPL makes sense. RAIntegration is fairly closely tied to RA, so a more permissive license would probably not do much good. A custom license could also be better if we want to restrict the ability of a third party to distribute derivatives that may be less secure.

MIT makes sense for rcheevos on the other hand, because it is not as dependent on a specific back-end, so I hope it remains licensed permissively.
