### ISSUE TITLE
[Suggestion] Split ResetIf into AltResetIf and GlobalResetIf

### ISSUE THREAD

**Issue by Kisumebuckets** [RetroAchievements/RAIntegration#612] opened 2020-09-30 18:10 UTC
I'd like to use a ResetIf inside of an AltGroup but only have it reset conditions inside of the AltGroup.  Currently ResetIfs will reset every condition no matter which AltGroup they are in.  My proposal would be to have Global ResetIf (similar to the current ResetIf), and a new feature, AltResetIf.  AltResetIf will only reset conditions that are inside it's shared AltGroup.  It also will only reset Core if used in Core, while leaving conditions in Alt Groups alone.

This would help me with coding more efficient save protection among some other things.

**Comment by Jamiras** [comment] 2020-09-30 18:28
Duplicate of #152 

See also #512

It seems like `ResetNext` would be the more desirable solution as it gives complete control over exactly what's being reset, and wouldn't require segregating the logic into an alt group. In almost all cases, a `ResetIf` is only really targeting a single condition anyway.

**Closed** 2021-01-08 03:59 UTC
Labels: duplicate
